# Sample workflow for building and deploying an Angular project to GitHub Pages
name: Deploy Angular App with GitHub Pages

on:
  # Trigger the workflow on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allow manual triggering from the Actions tab
  workflow_dispatch:

# Set permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Build Angular App
        run: npm run build -- --prod

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: ./docs

  # Deployment job
  deploy:
    environment:
      name: GitHub Pages
      url: ${{ steps.deployment.outputs.public-url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
